[package]
name = "concurrency-programming-book-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# signal-hook = "0.3"
futures = "0.3.13"
nix = "0.20.0"